---
    - name: MySql - Installation de mysql-server (Ubuntu)
      apt:
        pkg: mysql-server
        update_cache: yes
        cache_valid_time: 86400
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: MySql - Installation de mariadb-server (Debian)
      apt:
        pkg: mariadb-server
        update_cache: yes
        cache_valid_time: 86400
        state: present
      when: ansible_distribution == 'Debian'

    - name: MySql - Installation des dépendances Python MySQL
      apt:
        pkg:
          - python3-pymysql
        update_cache: yes
        cache_valid_time: 86400
        state: present

    - name: MySql - Démarrage du service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: MySql - Autoriser les connexions distantes (bind-address)
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'
      notify: Redémarrer MySQL

    - name: MySql - Creation de la base de données
      community.mysql.mysql_db:
        name: "{{ wp_db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: MySql - Création de l'utilisateur pour la base de données (serveur web distant)
      community.mysql.mysql_user:
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_password }}"
        host: "{{ hostvars[groups['serveurweb'][0]]['private_ip'] }}"
        priv: "{{ wp_db_name }}.*:ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
      no_log: true